=== DiegoJSan/XMLRepo/XML_Repo/Clientes/clientes.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT clientes (sede)*>
<!ELEMENT sede (direccion | empleado | fecha | descripcion | cliente)+>
<!ELEMENT direccion (#PCDATA)+>
<!ELEMENT empleado (#PCDATA)>
<!ELEMENT fecha (#CDATA)>
<!ELEMENT descripcion (#PCDATA)>
    <!ATTLIST descripcion Solvente CDATA #IMPLIED>
    <!ATTLIST descripcion Insolvente CDATA #IMPLIED>
<!ELEMENT cliente (#PCDATA)>
<!ELEMENT cliente (numeroVivienda | coste | resumen | plazo)*>
<!ELEMENT numeroVivienda (#PCDATA)>
<!ELEMENT coste (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT plazo ANY>

=== DiegoJSan/XMLRepo/XML_Repo/Clientes/clientes_D.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<clientes>
    <sede codigoSede= "A1234567">
        <direccion>Sevilla</direccion>
        <direccion>Sevilla</direccion>
        <empleado>Francisco</empleado>
        <fecha>22/11/2020</fecha>
        <descripcion>Casa adosada</descripcion>
        <cliente codigoCliente= "ABC-123">
            <numeroVivienda>1</numeroVivienda>
            <coste>132674.64</coste>
            <resumen>Solvente</resumen>
            <plazo>25</plazo>
        </cliente>
    </sede>
</clientes>
