<?xml version="1.0" encoding="UTF-8"?> <!--Instrucciones de procesamiento-->
<!DOCTYPE BDedicionesAranda 
[
<!ELEMENT edicionesAranda (cabecera, tabla)>
<!ELEMENT cabecera (titulo, contenido, descripcion, fecha)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ATTLIST fecha date CDATA #REQUIRED>
<!ELEMENT tabla (region+, triMestre, libros_vendidos)>
<!ELEMENT region (norte | centro | sur ) >
<!ELEMENT norte (#PCDATA | trimestre | librosVendidos)*>
<!ELEMENT centro (#PCDATA | trimestre | librosVendidos)*>
<!ELEMENT sur (#PCDATA | trimestre | librosVendidos)*>
<!ELEMENT trimestre (#PCDATA)>
<!ELEMENT librosVendidos (#PCDATA)>
<!ELEMENT triMestre (#PCDATA)>
<!ELEMENT libros_vendidos (#PCDATA)>
]>
<edicionesAranda>
    <cabecera>
        <titulo>Ediciones Aranda</titulo>
        <contenido>Informe regional de ventas</contenido>
        <descripcion>Descripci√≥n: Informe de ventas para regiones Norte, Centro y Sur</descripcion>
        <fecha>Fecha: 30/12/2009</fecha>
    </cabecera>
    <tabla>
        <region>Norte
            <trimestre>1</trimestre>
                <librosVendidos>24000</librosVendidos>
            <trimestre>2</trimestre>
                <librosVendidos>38600</librosVendidos>
            <trimestre>3</trimestre>
                <librosVendidos></librosVendidos>
            <trimestre>4</trimestre>
                <librosVendidos></librosVendidos>
        </region>
        <region>Centro
            <trimestre>1</trimestre>
                <librosVendidos></librosVendidos>
            <trimestre>2</trimestre>
                <librosVendidos>16080</librosVendidos>
            <trimestre>3</trimestre>
                <librosVendidos>25000</librosVendidos>
            <trimestre>4</trimestre>
                <librosVendidos>29000</librosVendidos>
        </region>
        <region>
            <sur>Sur
                <trimestre>1</trimestre>
                    <librosVendidos>27000</librosVendidos>
                <trimestre>2</trimestre>
                    <librosVendidos>31400</librosVendidos>
                <trimestre>3</trimestre>
                    <librosVendidos>40100</librosVendidos>
                <trimestre>4</trimestre>
                    <librosVendidos>30000</librosVendidos>
            </sur>
        </region>
        <triMestre>Trimestre</triMestre>
        <libros_vendidos>Libros Vendidos</libros_vendidos>
    </tabla>
</edicionesAranda>